"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>{children}</Providers>
        <footer className="border-t border-white/20">
          <div className="max-w-screen-xl mx-auto flex justify-between items-center h-20">
            <div>dhoniaridho</div>
            <div className="font-righteous">dhoniaridho.</div>
            <div>dhoniaridho</div>
          </div>
        </footer>
      </body>
    </html>
  );
}
